version: "3.3"

services:
  eng-barclays-adapter:
    image: "jumo/eng-barclays-adapter:{{ VERSION }}"
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
    environment:
      - SECRETS_FILE=/run/secrets/eng-barclays-adapter-v{{ VERSION }}
      - BARCLAYS_ADAPTER_AWS_ACCESS_KEY_ID={{ BARCLAYS_ADAPTER_AWS_ACCESS_KEY_ID }}
      - BARCLAYS_ADAPTER_AWS_SECRET_ACCESS_KEY={{ BARCLAYS_ADAPTER_AWS_SECRET_ACCESS_KEY }}
    secrets:
      - source: "eng-barclays-adapter-v{{ VERSION }}"
    networks:
      - traefik_traefik
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        traefik.port: 8080
        traefik.frontend.rule: "Host:barclays-adapter.internal.staging.jumo.world,barclays-adapter-api.external.staging.jumo.world"
        traefik.docker.network: "traefik_traefik"
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 70s
        order: start-first
        failure_action: rollback
networks:
  traefik_traefik:
    external: true

secrets:
  eng-barclays-adapter-v{{ VERSION }}:
    file: ./eng-barclays-adapter
